/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.kayteam.puntodeventa.screens;

import java.awt.Font;
import java.awt.event.KeyEvent;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.kayteam.puntodeventa.objects.Product;

/**
 *
 * @author segun
 */
public class CheckPricePanel extends javax.swing.JFrame {

    /**
     * Creates new form CheckPricePanel
     */
    public CheckPricePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        insertPCodeText = new javax.swing.JLabel();
        productCodeInput = new javax.swing.JTextPane();
        goBackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        insertPCodeText.setFont(new Font("Arial", Font.PLAIN, 40));
        insertPCodeText.setText("Ingrese el código del producto");

        productCodeInput.setFont(new Font("Arial", Font.PLAIN, 40));
        productCodeInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                productCodeInputKeyPressed(evt);
            }
        });

        goBackButton.setFont(new Font("Arial", Font.PLAIN, 40));
        goBackButton.setText("Volver");
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(insertPCodeText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(productCodeInput))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(goBackButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addComponent(insertPCodeText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productCodeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(goBackButton)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productCodeInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productCodeInputKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(!productCodeInput.getText().equals("")){
                try{
                    long productCode = Long.parseLong(productCodeInput.getText());
                    if(MainPanel.getProductManager().isProduct(productCode)){
                        Product product = MainPanel.getProductManager().getProducts().get(productCode);
                        String price = String.format("%,d", product.getPrice());
                        JLabel label = new JLabel("<html>Precio: $"+price+"<br/>Producto: "+product.getDescription()+"<html>");
                        label.setFont(new Font("Arial", Font.BOLD, 20));
                        JOptionPane.showMessageDialog(this, label, "Precio", JOptionPane.OK_CANCEL_OPTION);
                        clearInput();
                    }else{
                        JLabel label = new JLabel("Debe ingresar un código de producto válido.");
                        label.setFont(new Font("Arial", Font.BOLD, 20));
                        JOptionPane.showMessageDialog(this, label);
                        clearInput();
                    }
                }catch(Exception e){
                    JLabel label = new JLabel("Debe ingresar un código de producto válido.");
                    label.setFont(new Font("Arial", Font.BOLD, 20));
                    JOptionPane.showMessageDialog(this, label);
                    clearInput();
                }
            }else{
                JLabel label = new JLabel("Debe ingresar un código de producto válido.");
                label.setFont(new Font("Arial", Font.BOLD, 20));
                JOptionPane.showMessageDialog(this, label);
                clearInput();
            }
        }
    }//GEN-LAST:event_productCodeInputKeyPressed

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_goBackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckPricePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckPricePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckPricePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckPricePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckPricePanel().setVisible(true);
            }
        });
    }

    private void clearInput(){
        Timer timer = new Timer();
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                productCodeInput.setText("");
            }
        }, 1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton goBackButton;
    private javax.swing.JLabel insertPCodeText;
    private javax.swing.JTextPane productCodeInput;
    // End of variables declaration//GEN-END:variables
}